### ISSUE TITLE
Expansion packs

### ISSUE THREAD

**Issue by chrislambert** [youngj/EnvayaSMS#19]
I'm hitting the expansion pack limits. Any chance you can post additional expansion packs, or maybe instructions on how to create them?

Or point me to where they are in case I'm missing something. Thanks!

**Comment by youngj** [comment]
Sure, I can post new ones. How many messages are you trying to send per hour?

**Comment by youngj** [comment]
Just added 4 more expansion packs on https://github.com/youngj/EnvayaSMS/downloads (so you could send up to 900 SMS/hour)

**Comment by chrislambert** [comment]
Great, that's pretty helpful. I'd like the flexibility to burst as needed on an hourly basis, and the phone (MyTouch 3G) seems to be able to send ~20/minute. 900/hour should be fine.

Although for some reason, Github is 404'ing packs 6 and 7. 5 and 8 worked fine.

**Comment by youngj** [comment]
Packs 6 and 7 should be fixed now, thanks for letting me know.

**Comment by magixbox** [comment]
900 SMS per hour is almost the phone limit in theory -- given 4 seconds to send a SMS. Love it.

**Comment by BenasPaulikas** [comment]
Why do we need these extension packs :D ? Why not all are in main app OP ?

**Comment by BenasPaulikas** [comment]
+ After installing extension pack we still get message 

Can't send outgoing SMS: maximum limit of 100 in 1 hour reached\nTo increase this limit, install an expansion pack.

**Comment by dripschrisstevens** [comment]
> 
> 
>     * After installing extension pack we still get message
> 
> 
> Can't send outgoing SMS: maximum limit of 100 in 1 hour reached\nTo increase this limit, install an expansion pack.

@BenasPaulikas I ran into the same issue? Did you ever get around this?? I can clearly see the expansion packs installed but Envaya isn't recognizing that they're installed

**Comment by sundian** [comment]
> > ```
> > * After installing extension pack we still get message
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can't send outgoing SMS: maximum limit of 100 in 1 hour reached\nTo increase this limit, install an expansion pack.
> 
> @BenasPaulikas I ran into the same issue? Did you ever get around this?? I can clearly see the expansion packs installed but Envaya isn't recognizing that they're installed

Same issue. I think expansion packages acts like another apps. Only one app are allowed to send up to 100 sms per hour. But new android versions not allow app to see installed packages. If you android has no sms rate limit, app shouldn't  limit. Need to try increase constant OUTGOING_SMS_MAX_COUNT value to 1000 (in App.java:139) and rebuild projcect. Should help. I will try.

**Comment by koderov** [comment]
Hello, Any new links to the expansion packs, links provided are all dead??
